---
apiVersion: v1
kind: Secret
metadata:
  name: example-baremetalhost-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: example-baremetalhost
spec:
  online: true
  bmc:
    address: ipmi://10.132.47.106:623
    credentialsName: example-baremetalhost-secret

